package com.hifnawy.alquran.view.player.widgets

import android.content.Context
import android.content.res.Resources.NotFoundException
import android.graphics.Bitmap
import android.graphics.drawable.BitmapDrawable
import androidx.appcompat.content.res.AppCompatResources
import androidx.core.graphics.scale
import com.hifnawy.alquran.shared.QuranApplication
import com.hifnawy.alquran.shared.R
import com.hifnawy.alquran.shared.utils.DrawableResUtil.surahDrawables
import com.hifnawy.alquran.view.player.widgets.PlayerWidgetBitmaps.BITMAP_SIZE
import com.hifnawy.alquran.view.player.widgets.PlayerWidgetBitmaps.defaultSurahBitmap
import com.hifnawy.alquran.view.player.widgets.PlayerWidgetBitmaps.surahImages
import com.hoko.blur.HokoBlur

/**
 * A singleton object that pre-loads and caches bitmaps for use in the player widget.
 *
 * This object is responsible for creating and storing both standard and blurred versions
 * of surah images. By pre-loading these bitmaps into memory, it ensures smooth and
 * efficient updates to the widget's UI, avoiding the performance overhead of loading
 * and processing images on-the-fly during widget updates.
 *
 * The bitmaps are scaled to a standard size [BITMAP_SIZE] for consistency.
 * A default image is provided for cases where a specific surah image is not available.
 *
 * The list of all surah images, including their blurred counterparts, is available via
 * the [surahImages] property.
 *
 * @author AbdElMoniem ElHifnawy
 *
 * @see PlayerWidget for usage in updating the widget.
 */
object PlayerWidgetBitmaps {

    /**
     * A data class to hold both the standard and blurred bitmap representations of a Surah's image.
     * This is used for displaying Surah images in the player widget and its background.
     *
     * @property bitmap [Bitmap] The original, clear bitmap image for the Surah.
     * @property blurredBitmap [Bitmap] A blurred version of the [bitmap], typically used for background effects.
     *
     * @author AbdElMoniem ElHifnawy
     */
    data class SurahImage(val bitmap: Bitmap, val blurredBitmap: Bitmap)

    /**
     * The target width and height, in pixels, for all surah and blurred surah bitmaps.
     * This ensures consistency and helps manage memory usage for the player widget.
     *
     * @return [Int] The target width and height, in pixels, for all surah and blurred surah bitmaps.
     */
    private const val BITMAP_SIZE = 256

    /**
     * A scaled bitmap representation of the default Surah image.
     * This is used as a fallback or default display when a specific Surah's image is not available.
     * The bitmap is scaled to a standard size [BITMAP_SIZE] for consistency in the UI.
     *
     * @return [Bitmap] The scaled default bitmap for a Surah.
     */
    val defaultSurahBitmap = with(QuranApplication.applicationContext) {
        R.drawable.surah_name.surahBitmap.scale(width = BITMAP_SIZE, height = BITMAP_SIZE, filter = false)
    }

    /**
     * A blurred and scaled bitmap representation of the default Surah image.
     * This is generated by applying a Gaussian blur effect to the [defaultSurahBitmap]
     * using the HokoBlur library. It serves as a fallback for the player widget's
     * background when a specific Surah's blurred image is not available.
     *
     * @return [Bitmap] The blurred and scaled default bitmap for a Surah.
     */
    val defaultSurahBlurredBitmap = HokoBlur.with(QuranApplication.applicationContext)
        .scheme(HokoBlur.SCHEME_NATIVE)
        .mode(HokoBlur.MODE_GAUSSIAN)
        .radius(5)
        .sampleFactor(2.0f)
        .processor()
        .blur(defaultSurahBitmap)
        .scale(width = BITMAP_SIZE, height = BITMAP_SIZE, filter = false)

    /**
     * A pre-populated list of [SurahImage] objects, one for each Surah in the Quran.
     *
     * This list is initialized when the [PlayerWidgetBitmaps] object is first accessed.
     * It contains both the standard and blurred bitmaps for all 114 Surahs, plus a default
     * image at index 0. This allows for quick, zero-based, direct access to the image for
     * any given Surah number (e.g., `surahImages[ surahNumber ]`).
     *
     * The list is constructed by:
     * 1. Starting with a default [SurahImage] at index 0, which serves as a fallback.
     * 2. Mapping over the `surahDrawables` list, which contains drawable resource IDs for each Surah.
     * 3. For each drawable, it creates a scaled bitmap and a corresponding blurred version.
     * 4. These are then wrapped in a [SurahImage] data class and added to the list.
     *
     * The resulting list has 115 elements (1 default + 114 Surahs).
     *
     * @return [List] A [List] of [SurahImage] A list containing the default image followed by images for all 114 Surahs.
     */
    val surahImages = listOf<SurahImage>(
            SurahImage(bitmap = defaultSurahBitmap, blurredBitmap = defaultSurahBlurredBitmap),
    ) + surahDrawables.map { drawableId ->
        val surahBitmap = with(QuranApplication.applicationContext) { drawableId.surahBitmap }
        val surahBlurredBitmap = HokoBlur.with(QuranApplication.applicationContext)
            .scheme(HokoBlur.SCHEME_NATIVE)
            .mode(HokoBlur.MODE_GAUSSIAN)
            .radius(5)
            .sampleFactor(2.0f)
            .processor()
            .blur(surahBitmap)
            .scale(width = BITMAP_SIZE, height = BITMAP_SIZE, filter = false)

        SurahImage(bitmap = surahBitmap, blurredBitmap = surahBlurredBitmap)
    }

    /**
     * An extension property on [Int] that converts a drawable resource ID into a [Bitmap].
     *
     * This property assumes that the integer (`this`) is a valid `@DrawableRes` ID.
     * It uses the provided [Context] from the `context` receiver to access the drawable
     * resource, casts it to a [BitmapDrawable], and then extracts the underlying [Bitmap].
     *
     * This is a convenience helper to simplify the conversion of drawable resources to bitmaps
     * within the scope of [PlayerWidgetBitmaps].
     *
     * @receiver [Int] The drawable resource ID to be converted.
     *
     * @return [Bitmap] The bitmap representation of the drawable resource.
     *
     * @throws ClassCastException if the drawable resource is not a [BitmapDrawable].
     * @throws NotFoundException if the given ID does not exist.
     */
    context(context: Context)
    private val Int.surahBitmap get() = (AppCompatResources.getDrawable(context, this) as BitmapDrawable).bitmap.scale(width = BITMAP_SIZE, height = BITMAP_SIZE, filter = false)
}
